# Generated by Django 4.2 on 2023-05-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20, unique=True)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification", models.CharField(max_length=20)),
                ("notification_date", models.CharField(max_length=20)),
                ("notification_time", models.CharField(max_length=20)),
                ("users_type", models.CharField(max_length=20)),
                ("notification_status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="subadmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subadmin_name", models.CharField(max_length=20)),
                ("subadmin_district", models.CharField(max_length=20)),
                ("subadmin_city", models.CharField(max_length=20)),
                ("subadmin_dob", models.CharField(max_length=20)),
                ("subadmin_pincode", models.CharField(max_length=20)),
                ("subadmin_phoneno", models.CharField(max_length=20)),
                ("subadmin_email", models.CharField(max_length=20)),
                ("subadmin_gender", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "subadmin_loginid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jalanidhiapp.log",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="panchayath_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("panchayath_type", models.CharField(max_length=20)),
                ("panchayath_name", models.CharField(max_length=20)),
                ("ward_no", models.CharField(max_length=20)),
                ("panchayath_status", models.CharField(max_length=20)),
                (
                    "sub_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jalanidhiapp.subadmin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="meter_reader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meter_reader_name", models.CharField(max_length=20)),
                ("meter_reader_district", models.CharField(max_length=20)),
                ("meter_reader_city", models.CharField(max_length=20)),
                ("meter_reader_dob", models.CharField(max_length=20)),
                ("meter_reader_pincode", models.CharField(max_length=20)),
                ("meter_reader_phoneno", models.CharField(max_length=20)),
                ("meter_reader_email", models.CharField(max_length=20)),
                ("meter_reader_gender", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "meter_reader_loginid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jalanidhiapp.log",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("house_name", models.CharField(max_length=20)),
                ("dob", models.CharField(max_length=20)),
                ("house_no", models.CharField(max_length=20)),
                ("aadhar_no", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=20)),
                ("pin_code", models.CharField(max_length=20)),
                ("phone_no", models.CharField(max_length=20)),
                ("panchayath_type", models.CharField(max_length=20)),
                ("panchayath_name", models.CharField(max_length=20)),
                ("ward_no", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "login_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jalanidhiapp.log",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="complaintRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complaint", models.CharField(max_length=20)),
                ("complaint_time", models.CharField(max_length=20)),
                ("complaint_date", models.CharField(max_length=20)),
                ("complaint_status", models.CharField(max_length=20)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jalanidhiapp.consumer",
                    ),
                ),
            ],
        ),
    ]
