# Generated by Django 4.1.5 on 2023-05-08 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0002_panchayath_details_meter_reader"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaints_Replay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complaint", models.CharField(max_length=500)),
                ("date", models.DateField()),
                ("replay", models.CharField(default="No Replay", max_length=500)),
                ("complaint_status", models.CharField(max_length=10)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jalanidhiapp.consumer",
                    ),
                ),
            ],
        ),
    ]
