# Generated by Django 4.1.5 on 2023-05-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0003_complaints_replay"),
    ]

    operations = [
        migrations.CreateModel(
            name="connection_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connection_amt", models.IntegerField()),
                ("connection_status", models.CharField(max_length=50)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jalanidhiapp.consumer",
                    ),
                ),
            ],
        ),
    ]
