# Generated by Django 4.1.5 on 2023-05-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0004_connection_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="users_type",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_date",
            field=models.DateField(),
        ),
    ]
