# Generated by Django 4.1.5 on 2023-05-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0005_remove_notification_users_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="meter_reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_meter_reading", models.CharField(max_length=20)),
                ("meter_reading_date", models.CharField(max_length=20)),
                ("meter_reading_duedate", models.CharField(max_length=20)),
                ("meter_reading_price", models.CharField(max_length=20)),
                ("meter_reading_status", models.CharField(max_length=20)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jalanidhiapp.consumer",
                    ),
                ),
                (
                    "meter_reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jalanidhiapp.meter_reader",
                    ),
                ),
            ],
        ),
    ]
