# Generated by Django 4.1.5 on 2023-05-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0006_meter_reading"),
    ]

    operations = [
        migrations.CreateModel(
            name="payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reading_amount", models.CharField(max_length=20)),
                ("read_status", models.CharField(max_length=20)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jalanidhiapp.consumer",
                    ),
                ),
            ],
        ),
    ]
