# Generated by Django 4.2 on 2023-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0007_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection_details",
            name="panchayath_name",
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connection_details",
            name="panchayath_type",
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connection_details",
            name="ward_no",
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meter_reader",
            name="meter_reader_destination",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
