# Generated by Django 4.2 on 2023-05-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0008_connection_details_panchayath_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumer",
            name="category_proof",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
