# Generated by Django 4.2 on 2023-05-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0009_consumer_category_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection_details",
            name="panchayath_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="connection_details",
            name="panchayath_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="connection_details",
            name="ward_no",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="consumer", name="aadhar_no", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="category_proof",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="consumer", name="house_no", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="consumer", name="phone_no", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="consumer", name="pin_code", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="consumer", name="ward_no", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="meter_reader",
            name="meter_reader_phoneno",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="meter_reader",
            name="meter_reader_pincode",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="panchayath_details",
            name="ward_no",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="subadmin", name="subadmin_phoneno", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="subadmin", name="subadmin_pincode", field=models.IntegerField(),
        ),
    ]
