# Generated by Django 4.1.5 on 2023-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0010_alter_connection_details_panchayath_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaints_replay",
            name="consumer_name",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consumer",
            name="aadhar_no",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="house_no",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="phone_no",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="pin_code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="ward_no",
            field=models.CharField(max_length=10),
        ),
    ]
