# Generated by Django 4.1.5 on 2023-06-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0012_complaints_replay_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaints_replay",
            name="category",
        ),
        migrations.AddField(
            model_name="connection_details",
            name="category",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
