# Generated by Django 4.1.5 on 2023-06-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jalanidhiapp", "0013_remove_complaints_replay_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection_details",
            name="consumer_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="consumer_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
